import React from "react";

import Link from "next/link";

import Image from "next/image";

import { agent, agent1, agent2, agent3 } from "../../../../public/images";
import { Button } from "@/components/ui/button";
import Title from "@/components/Layout/Title";
import FinancialReportSection from "@/components/Layout/FinancialReportSection";

const termData = [
  {
    title: "Register with INZO Enzo",
    desc: "Becoming our IB is very simple – no paperwork, no costs, and it only takes 30 seconds to get started.",
    img: agent3,
  },
  {
    title: "Invite Traders",
    desc: "Everything is ready for you to promote us – links, logos, banners, and landing pages. Mix and match them any way you like.",
    img: agent2,
  },
  {
    title: "Earn Commissions",
    desc: "Earn up to $7 per lot on a Standard Account for every trade your client makes.",

    img: agent1,
  },
];

const page = () => {
  const data = [
    { value: 5, textValue: "Million", text: "Monthly ", text2: "Withdrawal" },
    { value: 50, textValue: "K", text: "MonthlyIB", text2: "Withdrawal" },
    {
      value: 75,
      textValue: "Billion",
      text: "Monthly ",
      text2: "Trading Range",
    },
    { value: 30, textValue: "K", text: "Monthly ", text2: "Active Client" },
  ];
  return (
    <>
      <div className="w-full h-full bg-[#0F2147]  max-md:pb-2 pb-20">
        <div className="w-full  bg-optimizer_ourTeamBg   bg-cover bg-top bg-no-repeat  ">
          <div className="w-full pt-[15rem]  max-xs:bg-banner_page_mobile bg-ourTeamBg   bg-cover bg-top bg-no-repeat  z-[100]">
            <div className="w-full   h-full flex flex-col justify-center items-end max-sm:items-center  ">
              <div className="flex flex-col gap-2 text-center w-full ">
                <div className="flex gap-2 text-5xl max-md:text-3xl font-semibold text-center justify-center">
                  <h1 className={`text-secondary `}>{`Agent`}</h1>
                  <h1 className={`text-white `}>{`Program`}</h1>
                </div>
                <div
                  className="flex flex-col gap-2 text-white justify-center 
              items-center max-md:text-[18px] text-[22px] max-md:px-4 px-[5rem] pt-5"
                >
                  <p>Invite clients to INZO Enzo. They trade - you earn!</p>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div
          className="relative  h-fit bg-[#62729400] 
   "
        >
          <div className="relative z-10  mt-10 flex flex-col md:flex-row md:ms-10  md:pe-10 gap-5">
            <div className="w-full md:w-[700px] h-full flex flex-col ps-5  max-md:pe-3 pe-24 justify-center max-md:gap-5 gap-8 text-white ">
              <p className="text-lg max-md:text-lg leading-8">
                Introducing Brokers (IBs) are companies or individuals
                worldwidern money by referring clients to INZO Enzo. We partner
                who eawith our IBs to strive for success by offering them one of
                the best IB commission rates among Forex brokers. Contact us to
                learn more about our offer.
              </p>
              <p className="text-lg max-md:text-lg leading-8">
                Our IB program is not limited to companies or individuals with
                large lists of potential clients – every trade generated by your
                referral will earn you money.
              </p>
              <p className="text-lg max-md:text-lg leading-8">
                Introducing INZO Enzo is easy – our IB Room provides you with
                advanced tools for managing funds and accounts, as well as a
                range of ready-to-use promotional materials to effectively
                attract new clients.
              </p>
            </div>
            <div className="w-[85%]] md:w-[600px] h-[300px] md:h-[450px] max-md:mx-auto mt-6 md:mt-1 ">
              <Image src={agent} className="h-full w-full " alt="inzo" />
            </div>
          </div>

          <div className="relative max-md:mt-[100px]  mx-auto flex flex-col items-center   z-10 md:translate-y-32">
            <div className="grid grid-cols-[repeat(1,minmax(0,90%))] md:grid-cols-[repeat(3,minmax(0,400px))] place-content-center max-md:gap-y-24 gap-y-5  ">
              {termData.map((item, index) => (
                <div
                  className={`flex flex-col items-center justify-start w-full md:w-[380px]
                 h-[235px] md:h-[260px] text-white  mx-auto p-4 md:p-5 pt-8 pb-0 rounded-3xl 
                  border border-[#00C0FF]  relative bg-custom-gradient text-center`}
                  key={index}
                >
                  <div className="mt-6 md:mt-12">
                    <p className="text-[21px] md:text-2xl font-bold ">
                      {item.title}
                    </p>
                    <p className="text-[18px] md:text-[1.2rem] px-0 md:px-3 pt-2">
                      {item.desc}
                    </p>
                  </div>
                  <Image
                    src={item.img}
                    width={105}
                    height={100}
                    className="absolute -top-14 left-[130x] md:left-[38%]"
                    alt="inzo"
                  />
                </div>
              ))}
            </div>
            <Link href="/#">
              <Button
                className="button-border2 px-10 py-6 
              font-semibold text-sm mx-auto mt-16 max-md:!rounded-[8px]"
              >
                Become an Agent
              </Button>
            </Link>

            <div
              className="block md:hidden absolute bottom-[15rem] left-0 right-0 
        bg-agentMob_Bg h-[75%] bg-cover bg-left -z-10"
            ></div>
          </div>

          <div
            className="hidden md:block absolute bottom-24 left-0 right-0 
          bg-agent_Bg h-[50%] bg-cover bg-center"
          ></div>

          <div
            className="absolute bottom-0 left-0 right-0 
          bg-teamStars_Bg  bg-no-repeat  bg-center h-[10%]"
          ></div>
        </div>

        <div
          className="relative max-md:pb-0 pb-12 max-md:px-6 bg-[#0F2147] 
           h-full md:h-[100vh] flex flex-col 
    items-center justify-center"
        >
          <div className="absolute top-0 left-0 right-0 bg-teamStars_Bg  bg-no-repeat  bg-center h-[70%]"></div>
          <div className="mt-[0px] md:mt-[250px]">
            <Title
              title1={`Financial`}
              title2={`Report`}
              classNameImg="hidden"
            />
            <div className="mt-[110px]">
              <FinancialReportSection
                data={data}
                className="!gap-16 md:!gap-20"
              />
            </div>
          </div>
        </div>
        {/*     */}
      </div>
    </>
  );
};

export default page;
