





import {NextIntlClientProvider} from 'next-intl';
import {getMessages} from 'next-intl/server';
import {notFound} from 'next/navigation';
import {routing} from '@/i18n/routing';
import localFont from "next/font/local";
import Header from '@/components/Layout/Header';
import "./globals.css";
import Footer from '@/components/Layout/Footer';
export const metadata = {
  title: "Inzo",
  description: "Generated by create next app",
};

const myFont = localFont({ src: "./../../../public/font/Tajawal Regular.ttf" });
export default async function LocaleLayout({
  children,
  params: {locale}
}) {
  // Ensure that the incoming `locale` is valid
  if (!routing.locales.includes(locale)) {
    notFound();
  }
 
  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages();
 
  return (
    <html lang={locale}>
      <body className={` ${myFont.className}`}>
        <NextIntlClientProvider messages={messages}>
        <Header />
         {children}
         <Footer/>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}













